# Generated by Django 4.1.2 on 2022-10-27 18:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='files/photos')),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, size=None)),
                ('description', models.CharField(blank=True, max_length=450)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('year_photo', models.PositiveSmallIntegerField(blank=True)),
            ],
        ),
    ]
