# Generated by Django 4.1.2 on 2022-11-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_photos_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table_test',
        ),
    ]
