version: '3.9'

services:
  app:
    build: 
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    environment:
      - SECRET_KEY=djangodevsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=db_konnovv_website
      - DB_USER=devkonnov
      - DB_PASS=likeprogdbpass
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: db_konnovv_website
      POSTGRES_USER: devkonnov
      POSTGRES_PASSWORD: likeprogdbpass